'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Food', [{
      name: 'Nasi',
      calories: 129,
      serving_size: 100,
      serving_plate: 200,
      serving_bowl: 150,
      piece: 0,
      fat: 0.28,
      cholesterol: 0,
      protein: 2.66,
      carbohydrate: 27.9,
      sodium: 365,
      kalium: 35,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Ayam Panggang',
      calories: 201,
      serving_size: 85,
      serving_plate: 300,
      serving_bowl: 200,
      piece: 100,
      fat: 11.46,
      cholesterol: 74,
      protein: 23.01,
      carbohydrate: 0,
      sodium: 344,
      kalium: 187.97,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Brokoli Rebus',
      calories: 34,
      serving_size: 100,
      serving_plate: 150,
      serving_bowl: 100,
      piece: 0,
      fat: 0.37,
      cholesterol: 0,
      protein: 2.82,
      carbohydrate: 6.64,
      sodium: 33,
      kalium: 316,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Spaghetti Bolognese',
      calories: 161,
      serving_size: 100,
      serving_plate: 300,
      serving_bowl: 200,
      piece: 0,
      fat: 4.35,
      cholesterol: 0,
      protein: 6.09,
      carbohydrate: 23.91,
      sodium: 0,
      kalium: 0,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Ikan Panggang',
      calories: 126,
      serving_size: 100,
      serving_plate: 300,
      serving_bowl: 200,
      piece: 100,
      fat: 3.44,
      cholesterol: 73,
      protein: 21.94,
      carbohydrate: 0.33,
      sodium: 356,
      kalium: 341,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Pisang',
      calories: 107,
      serving_size: 120,
      serving_plate: 0,
      serving_bowl: 0,
      piece: 120,
      fat: 0.4,
      cholesterol: 0,
      protein: 1.31,
      carbohydrate: 27.41,
      sodium: 1,
      kalium: 429.6,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Telur Rebus',
      calories: 70,
      serving_size: 50,
      serving_plate: 0,
      serving_bowl: 0,
      piece: 50,
      fat: 4.65,
      cholesterol: 186,
      protein: 5.51,
      carbohydrate: 0.49,
      sodium: 122,
      kalium: 55.44,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Yoghurt Tanpa Gula',
      calories: 120,
      serving_size: 150,
      serving_plate: 200,
      serving_bowl: 150,
      piece: 0,
      fat: 17.99,
      cholesterol: 139,
      protein: 17.61,
      carbohydrate: 7.6,
      sodium: 460,
      kalium: 215.7,
      createdAt: new Date(),
      updatedAt: new Date(),
    },], {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Food', null, {});
  }
};
